const overviewActionTypes = {
  START_COLLECTING_OVERVIEW: "START_COLLECTING_OVERVIEW",
  STOP_COLLECTING_OVERVIEW: "STOP_COLLECTING_OVERVIEW",
  COLLECTION_SUCCESS_OVERVIEW: "COLLECTION_SUCCESS_OVERVIEW"
};

export default overviewActionTypes;
