export default {
  CHECK_OVERVIEW_DATA: "CHECK_OVERVIEW_DATA",
  CHECK_STATS_DATA: "CHECK_STATS_DATA",
  CONTAINER_WARNING_FOUND: "CONTAINER_WARNING_FOUND",
  NO_NOTIFICATION_NEEDED: "NO_NOTIFICATION_NEEDED",
  CLEAR_ALL_WARNINGS: "CLEAR_ALL_WARNINGS",
};
