version: "3"

services:    
  kerberos-db:
    image: postgres
    environment:
      POSTGRES_USER: kerberos
      POSTGRES_PASSWORD: Kerberos_Password1
      POSTGRES_DB: kerberos_db
    networks:
      - back

  kerberos:
    image: cfei/docker-kerberos
    ports:
      - 6000:6000
    environment:
      KERBEROS_ADMIN_PW: password
      KERBEROS_HOST_DNS: kerberos
      KERBEROS_REALM: CFEI.SECURE
      KERBEROS_API_PORT: 6000
      KERBEROS_POSTGRES_CONNECTION_STRING: "Host=kerberos-db;Port=5432;Database=kerberos_db;Username=kerberos;Password=Kerberos_Password1;"
    depends_on:
      - kerberos-db
    networks:
      - front
      - back
  
  zookeeper: # INFO - Zookeeper is dependant upon kerberos making a keytab for it first. Should kerberos support this or should it all just happen via the dashboard interface?
    image: cfei/zookeeper:2.0.0-beta
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181
      ZOO_AUTHENTICATION: KERBEROS
      ZOO_KERBEROS_PUBLIC_URL: kerberos
      ZOO_KERBEROS_API_URL: "http://kerberos:3000/get-keytab"
      ZOO_KERBEROS_API_USERNAME: zookeeper/161.35.145.163
      ZOO_KERBEROS_API_PASSWORD: zookeeperPassword
      ZOO_KERBEROS_REALM: CFEI.SECURE
      ZOO_REMOVE_HOST_AND_REALM: "true"
    networks: 
      - back

  dashboard-server:
    image: omvk97/docker-dashboard-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SERVER_NAME: SingleServer
    networks:
      - back

  interface-db:
    image: postgres
    environment:
      POSTGRES_USER: interface
      POSTGRES_PASSWORD: Interface_database_password1
      POSTGRES_DB: interface_db
    networks:
      - front
      - back

  interface:
    image: omvk97/docker-dashboard-interface
    ports:
      - 3001:3001
      - 5000:5000
    environment:
      DASHBOARDI_UI_PORT: 3001
      DASHBOARDI_SOCKET_SERVER_PORT: 5000
      DASHBOARDI_POSTGRES_CONNECTION_STRING: "Host=interface-database;Port=5432;Database=interface_db;Username=interface;Password=Interface_database_password1"
      DASHBOARDI_API_KEY: secureapiKey
      DASHBOARDI_JWT_KEY: cfeisecureJWTkey
      DASHBOARDI_INIT_USER_EMAIL: testUser@email.com
      DASHBAORDI_INIT_PASSWORD: testUserPassword%1.
    depends_on:
      - interface-db
      - dashboard-server
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
