version: "3"

services:
  interface:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    ports:
      - 1433:1433
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: Database_password1
