version: "3"

services:
  interface:
    image: omvk97/docker-dashboard-interface
    container_name: interface
    ports:
      - 3000:3000
      - 5000:5000
    environment: 
      UI_PORT: 3000
      DASHBOARD_POSTGRES_CONNECTION_STRING: "Host=161.35.145.151;Port=5432;Database=test;Username=admin;Password=Database_password1"
      KAFKA_URL: kafka1.cfei.dk:9092,kafka2.cfei.dk:9092,kafka3.cfei.dk:9092
      API_KEY: jahfgjwetkoj14h3i3289
