version: "3"

services:
  interface-database:
    image: postgres
    container_name: interface-database
    restart: always
    environment:
      POSTGRES_USER: interface
      POSTGRES_PASSWORD: Interface_database_password1
      POSTGRES_DB: interface_db

  interface:
    image: omvk97/dashboard-interface
    container_name: interface
    ports:
      - 3001:3001
      - 5000:5000
    environment:
      DASHBOARDI_UI_PORT: 3001
      DASHBOARDI_SOCKET_SERVER_PORT: 5000
      DASHBOARDI_KAFKA_URL: 161.35.156.138:9093
      DASHBOARDI_POSTGRES_CONNECTION_STRING: "Host=interface-database;Port=5432;Database=interface_db;Username=interface;Password=Interface_database_password1"
      DASHBOARDI_API_KEY: secureapiKey
      DASHBOARDI_JWT_KEY: secureJWTKeywhatifiasdhawrhawtkhawtrkh
      DASHBOARDI_API_DNS: https://localhost:5000
      DASHBOARDI_INIT_USER_EMAIL: testUser@email.com
      DASHBAORDI_INIT_PASSWORD: testUserPassword%1.
      DASHBOARDI_KERBEROS_PUBLIC_URL: 161.35.156.138
      DASHBOARDI_KERBEROS_REALM: KAFKA.SECURE
      DASHBOARDI_KERBEROS_API_URL: http://161.35.156.138:6000/get-keytab
      DASHBOARDI_KERBEROS_API_SERVICE_USERNAME: dashboardinterface/161.35.156.138
      DASHBOARDI_KERBEROS_API_SERVICE_PASSWORD: dashboardServerInterface
    depends_on:
      - interface-database
