version: "3"

services:
  interface-database:
    image: postgres
    container_name: interface-database
    restart: always
    environment:
      POSTGRES_USER: interface
      POSTGRES_PASSWORD: Interface_database_password1
      POSTGRES_DB: interface_db

  interface:
    image: omvk97/docker-dashboard-interface
    container_name: interface
    ports:
      - 3001:3001
      - 5000:5000
    environment: 
      DASHBOARDI_UI_PORT: 3001
      DASHBOARDI_SOCKET_SERVER_PORT: 5000
      DASHBOARDI_POSTGRES_CONNECTION_STRING: "Host=interface-database;Port=5432;Database=interface_db;Username=interface;Password=Interface_database_password1"
      DASHBOARDI_API_KEY: secureapiKey
      DASHBOARDI_API_DNS: https://localhost:5000
      DASHBOARDI_INIT_USER_EMAIL: testUser@email.com
      DASHBAORDI_INIT_PASSWORD: testUserPassword%1.
    depends_on: 
      - interface-database
