export const containerActionTypes = {
  RENAME_CONTAINER_SUCCESS: "RENAME_CONTAINER_SUCCESS",
  START_OR_STOP_CONTAINER_SUCCESS: "START_OR_STOP_CONTAINER_SUCCESS",
  RESART_CONTAINER_SUCCESS: "RESART_CONTAINER_SUCCESS",
  REMOVE_CONTAINER_SUCCESS: "REMOVE_CONTAINER_SUCCESS",
  RUN_CONTAINER_SUCCESS: "RUN_CONTAINER_SUCCESS",
  UPDATE_CONTAINER_CONFIGURATION_SUCCESS:
    "UPDATE_CONTAINER_CONFIGURATION_SUCCESS",
};

export const overviewActionTypes = {
  START_COLLECTING_OVERVIEW: "START_COLLECTING_OVERVIEW",
  STOP_COLLECTING_OVERVIEW: "STOP_COLLECTING_OVERVIEW",
  COLLECTION_SUCCESS_OVERVIEW: "COLLECTION_SUCCESS_OVERVIEW",
};

export const ressourceActionTypes = {
  START_COLLECTING_RESSOURCE: "START_COLLECTING_RESSOURCE",
  STOP_COLLECTING_RESSOURCE: "STOP_COLLECTING_RESSOURCE",
  COLLECTION_SUCCESS_RESSOURCE: "COLLECTION_SUCCESS_RESSOURCE",
};
