const GENERAL_SOCKET_ENDPOINT = "general";
const RESSOURCE_USAGE_ENDPOINT = "ressource_usage";
const NEWEST_OVERVIEW_DATA_REQUEST = "newest_overview_data";
const NEWEST_STATS_DATA_REQUEST = "newest_stats_data";

module.exports = {
  GENERAL_SOCKET_ENDPOINT,
  RESSOURCE_USAGE_ENDPOINT,
  NEWEST_OVERVIEW_DATA_REQUEST,
  NEWEST_STATS_DATA_REQUEST,
};
