const OVERVIEWDATA_FUNCTION = "SendOverviewData";
const STATSDATA_FUNCTION = "SendStatsData";
const NEWEST_OVERVIEW_DATA_REQUEST = "ReceiveNewestOverviewData";
const NEWEST_STATS_DATA_REQUEST = "ReceiveNewestStatsData";

module.exports = {
  OVERVIEWDATA_FUNCTION,
  STATSDATA_FUNCTION,
  NEWEST_OVERVIEW_DATA_REQUEST,
  NEWEST_STATS_DATA_REQUEST,
};
