const ressourceActionTypes = {
  START_COLLECTING_RESSOURCE: "START_COLLECTING_RESSOURCE",
  STOP_COLLECTING_RESSOURCE: "STOP_COLLECTING_RESSOURCE",
  COLLECTION_SUCCESS_RESSOURCE: "COLLECTION_SUCCESS_RESSOURCE"
};

export default ressourceActionTypes;
